Altering Data

In [1]:
import pandas as pd

In [2]:
people = {
    "first":["Shreyansh",'Jane','John'],
    "last":["Kumar",'Doe','Doe'],
    "email":["shre@gmail.com",'JaneDoe@gmail.com','JohnDoe@gmail.com']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com

In [5]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [20]:
# changing column name(M1)
df.columns = ['first_name', 'last_name', 'email']

In [21]:
df.columns

Index(['first_name', 'last_name', 'email'], dtype='str')

In [22]:
df

  first_name last_name              email
0  Shreyansh     Kumar     shre@gmail.com
1       Jane       Doe  JaneDoe@gmail.com
2       John       Doe  JohnDoe@gmail.com

In [23]:
# uppercase to lowercase and vice versa
# colmnn name have spaces and want to replace them
# in the above two cases we use list comprehension

In [28]:
# for example: I want to get all of the columns to be uppercase
df.columns = [x.lower() for x in df.columns]
df

  first name last name              email
0  Shreyansh     Kumar     shre@gmail.com
1       Jane       Doe  JaneDoe@gmail.com
2       John       Doe  JohnDoe@gmail.com

In [30]:
# For Example 2: Replace spaces with underscores
df.columns = df.columns.str.replace(' ', '_')
df

  first_name last_name              email
0  Shreyansh     Kumar     shre@gmail.com
1       Jane       Doe  JaneDoe@gmail.com
2       John       Doe  JohnDoe@gmail.com

In [35]:
# Example 3: We want to change some column (rename method and we will pass a dictionary)
df.rename(columns={
    'first_name':'first',
    'last_name': 'last'
},inplace=True)
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com

In [38]:
# Example 4: Updating data in rows
# Single value
df.loc[2] = ['John','Smith','JohnSmith@email.com']
df

       first   last                email
0  Shreyansh  Kumar       shre@gmail.com
1       Jane    Doe    JaneDoe@gmail.com
2       John  Smith  JohnSmith@email.com

In [42]:
# Multiple value
df.loc[2, ['last', 'email']] = ['Doe', 'JohnDoe@email.com']
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@email.com

In [45]:
# Example 5: To change only one value
df.loc[2, 'last'] = 'Smith'
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John  Smith  JohnDoe@email.com

In [46]:
# another way 
df.at[2, 'last'] = 'Doe'
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@email.com

In [51]:
# Common Mistake
filt=(df['email'] == 'JohnDoe@email.com')
df[filt]['last']='Smith'
df

C:\Users\Shreyansh kumar\AppData\Local\Temp\ipykernel_3316\3230418051.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filt]['last']='Smith'

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@email.com

In [52]:
filt=(df['email'] == 'JohnDoe@email.com')
df.loc[filt, 'last']='Smith'
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John  Smith  JohnDoe@email.com

In [55]:
# Example 6: Email Address to lowercase
df['email'] = df['email'].str.lower()
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  janedoe@gmail.com
2       John  Smith  johndoe@email.com

In [57]:
# 4methods
#1. apply---->used for calling a function on our values(works on either dataframe or series object)
#2. map
#3. applymap
#4. replace

In [58]:
df['email'].apply(len)

0    14
1    17
2    17
Name: email, dtype: int64

In [69]:
def update_email(email):
    return email.upper()

df['email'].apply(update_email) # changes from lowercase to uppercase
#-----------------------------------------------------------------------
# Prints the table
df['email'] = df['email'].apply(update_email)
df

       first   last              email
0  Shreyansh  Kumar     SHRE@GMAIL.COM
1       Jane    Doe  JANEDOE@GMAIL.COM
2       John  Smith  JOHNDOE@EMAIL.COM

In [ ]:
# Using