In [1]:
# importing libraries
import pandas as pd

In [2]:
people = {
    "first":["Shreyansh",'Jane','John'],
    "last":["Kumar",'Doe','Doe'],
    "email":["shre@gmail.com",'JaneDoe@gmail.com','JohnDoe@gmail.com']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com

In [8]:
# Comparisons
df['last']=='Doe'
# We get a series with a bunch of boolean value
# These boolean value corresponds to our dataframes
# TRUE--->criteria met
# FALSE---> criteria not satisfied

0    False
1     True
2     True
Name: last, dtype: bool

In [11]:
filt = (df['last']=='Doe')

In [13]:
#Method1
df[filt]

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In [15]:
#method2
df[df['last']=='Doe']

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In [18]:
#method3
df.loc[filt] #we can still pass the specific columns that we want

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In [19]:
df.loc[filt, 'email']

1    JaneDoe@gmail.com
2    JohnDoe@gmail.com
Name: email, dtype: str

In [20]:
# &------>and
# |-------> OR

In [22]:
# all of the rows that has the last name Doe and the first name is John
filt = (df['last']=='Doe') & (df['first']=='John')

In [23]:
df.loc[filt, 'email']

2    JohnDoe@gmail.com
Name: email, dtype: str

In [26]:
# the last name should be either ------- or -----------
filt = (df['last']=='Kumar') | (df['first']=='John')
df.loc[filt, 'email']

0       shre@gmail.com
2    JohnDoe@gmail.com
Name: email, dtype: str

In [29]:
# last name isn't Kumar or forst name isn't John
df.loc[~filt, 'email']

1    JaneDoe@gmail.com
Name: email, dtype: str