In [1]:
people = {
    "first":["Shreyansh",'Jane','John'],
    "last":["Kumar",'Doe','Doe'],
    "email":["shre@gmail.com",'JaneDoe@gmail.com','JohnDoe@gmail.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com

In [7]:
# Pandas doesn't actually enforce indexes being unique but mos the time it will be unique.

In [8]:
#View all of the email addresses
df['email']

0       shre@gmail.com
1    JaneDoe@gmail.com
2    JohnDoe@gmail.com
Name: email, dtype: str

In [10]:
# Setting email address as an index
df.set_index('email')

                       first   last
email
shre@gmail.com     Shreyansh  Kumar
JaneDoe@gmail.com       Jane    Doe
JohnDoe@gmail.com       John    Doe

In [11]:
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com

In [12]:
df.set_index('email',inplace=True)

In [13]:
df

                       first   last
email
shre@gmail.com     Shreyansh  Kumar
JaneDoe@gmail.com       Jane    Doe
JohnDoe@gmail.com       John    Doe

In [14]:
# Specifically at Index
df.index

Index(['shre@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com'], dtype='str', name='email')

In [15]:
# Indexes are the labels for these row

In [17]:
# Specific rows
df.loc['shre@gmail.com','last']

'Kumar'

In [18]:
# Reset Index Method
df.reset_index(inplace=True)

In [19]:
df

               email      first   last
0     shre@gmail.com  Shreyansh  Kumar
1  JaneDoe@gmail.com       Jane    Doe
2  JohnDoe@gmail.com       John    Doe