In [1]:
import pandas as pd

In [14]:
people = {
    "first":["Shreyansh",'Jane','John', 'Adam'],
    "last":["Kumar",'Doe','Doe','Doe'],
    "email":["shre@gmail.com",'JaneDoe@gmail.com','JohnDoe@gmail.com','a@email.com']
}

In [15]:
df = pd.DataFrame(people)

In [16]:
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com
3       Adam    Doe        a@email.com

# Sorting Single Columns

In [17]:
# Example1: Sorting by last name
df.sort_values(by='last')

       first   last              email
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com
3       Adam    Doe        a@email.com
0  Shreyansh  Kumar     shre@gmail.com

In [18]:
# Example2: Sort these values in descendding order
df.sort_values(by='last', ascending=False)

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com
3       Adam    Doe        a@email.com

# Sorting Multiple Columns

In [19]:
# Example 1:
# 1. last name in descending order
# 2. if the last name contain duplicate then have to sort the first name
df.sort_values(by=['last','first'], ascending=False)

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
2       John    Doe  JohnDoe@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
3       Adam    Doe        a@email.com

# Advanced Sorting Techniques

In [23]:
# Ex1:
# 1. last name in descending order
# 2. first name in ascending order
df.sort_values(by=['last','first'], ascending=[False, True], inplace=True)
df

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
3       Adam    Doe        a@email.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com

# Sorting index and series

In [25]:
# Example: Sorting the index(sort index)
df.sort_index()

       first   last              email
0  Shreyansh  Kumar     shre@gmail.com
1       Jane    Doe  JaneDoe@gmail.com
2       John    Doe  JohnDoe@gmail.com
3       Adam    Doe        a@email.com

In [26]:
# Example: Sorted Last Name
df['last'].sort_values()

3      Doe
1      Doe
2      Doe
0    Kumar
Name: last, dtype: str